name: Release Notes

on:
  release:
    types: [published]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 1knownothing/changelog-narrate@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
